version: "3.3"

services:
  nginx:
    container_name: nginx_skeleton
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
    networks:
      - internal_network

  php:
    build: ./Docker/php
    container_name: php_skeleton
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge