services:
    postgresql:
        build:
            context: ..
            dockerfile: docker/postgresql/Dockerfile
        container_name: database
        restart: always
        ports:
            - "${DB_PORT}:${DB_PORT}"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_HOST: ${DB_HOST}
            POSTGRES_PORT: ${DB_PORT}
        volumes:
            - db_app:/var/lib/postgresql/data
        networks:
            - database
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        container_name: php
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/html/var
            - symfony_app_vendor:/var/www/html/vendor
        networks:
            - app
            - database
            - message_queue
    nginx:
        build:
            context: ./nginx
        container_name: server
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_app_var:/var/www/html/var
            - symfony_app_vendor:/var/www/html/vendor
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        networks:
            - app
            - database
            - message_queue
        env_file:
            - .env.nginx.local
    rabbitmq:
        build:
            context: ./rabbitmq
        container_name: messenger
        ports:
            - "15672:15672"  # RabbitMQ Management UI
            - "5672:5672"    # RabbitMQ Transport Port
        networks:
            - message_queue

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    app:
        external: true
    message_queue:
        external: true
    database:
        external: true
